/*
Source code from https://github.com/yanbe/ssd1306-esp-idf-i2c
*/
#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "ssd1306.h"
#include "font.h"

#define SDA_PIN GPIO_NUM_4
#define SCL_PIN GPIO_NUM_15
#define RST_PIN GPIO_NUM_16

#define TAG "SSD1306"

unsigned char ssd1306Ready = 0;

#define I2C_TIMER 1

static void ssd1306PinsInit() {

	gpio_config_t io_conf;
	io_conf.intr_type = GPIO_PIN_INTR_DISABLE; //disable interrupt
	io_conf.mode = GPIO_MODE_OUTPUT; //set as output mode
	io_conf.pin_bit_mask = (1ULL << RST_PIN) ;//bit mask of the pins that you want to set,e.g.GPIO18/19
	io_conf.pull_down_en = 0; //disable pull-down mode
	io_conf.pull_up_en = 1;//enable pull-up mode
	gpio_config(&io_conf);//configure GPIO with the given settings

	//This pin is reset signal input. When the pin is pulled LOW, initialization of the chip is
	//executed. Keep this pin HIGH (i.e. connect to VDD) during normal operation.
	gpio_set_level(RST_PIN, 1);

	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};

	i2c_param_config(I2C_NUM_0, &i2c_config);

	i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);

}

static void ssd1306ModuleInit() {
	esp_err_t espRc;

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_CHARGE_PUMP, true);
	i2c_master_write_byte(cmd, 0x14, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_SEGMENT_REMAP, true); // reverse left-right mapping
	i2c_master_write_byte(cmd, OLED_CMD_SET_COM_SCAN_MODE, true); // reverse up-bottom mapping

	i2c_master_write_byte(cmd, OLED_CMD_DISPLAY_ON, true);
	i2c_master_stop(cmd);

	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
	if (espRc == ESP_OK) {
		ESP_LOGI(TAG, "OLED configured successfully");
		ssd1306Ready = 1;
	} else {
		ESP_LOGE(TAG, "OLED configuration failed. code: 0x%.2X", espRc);
	}
	i2c_cmd_link_delete(cmd);
}

// void ssd1306TaskDisplayPattern(void *ignore) {

// 	if (!ssd1306Ready){
// 		vTaskDelete(NULL);
// 		return;
// 	}

// 	i2c_cmd_handle_t cmd;

// 	for (uint8_t i = 0; i < 8; i++) {
// 		cmd = i2c_cmd_link_create();
// 		i2c_master_start(cmd);
// 		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
// 		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
// 		i2c_master_write_byte(cmd, 0xB0 | i, true);
// 		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
// 		for (uint8_t j = 0; j < 128; j++) {
// 			i2c_master_write_byte(cmd, 0xFF >> (j % 8), true);
// 		}
// 		i2c_master_stop(cmd);
// 		i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
// 		i2c_cmd_link_delete(cmd);
// 	}

// 	vTaskDelete(NULL);
// }

static void ssd1306CLS(void) {

	if (!ssd1306Ready){
		return;
	}

	i2c_cmd_handle_t cmd;

	uint8_t zero[128] = {0};
	for (uint8_t i = 0; i < 8; i++) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0xB0 | i, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, zero, 128, true);
		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
		i2c_cmd_link_delete(cmd);
	}
}


// void ssd1306TaskContrast(void *ignore) {

// 	if (!ssd1306Ready){
// 		vTaskDelete(NULL);
// 		return;
// 	}

// 	i2c_cmd_handle_t cmd;

// 	uint8_t contrast = 0;
// 	uint8_t direction = 1;
// 	while (true) {
// 		cmd = i2c_cmd_link_create();
// 		i2c_master_start(cmd);
// 		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
// 		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
// 		i2c_master_write_byte(cmd, OLED_CMD_SET_CONTRAST, true);
// 		i2c_master_write_byte(cmd, contrast, true);
// 		i2c_master_stop(cmd);
// 		i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
// 		i2c_cmd_link_delete(cmd);
// 		vTaskDelay(1/portTICK_PERIOD_MS);

// 		contrast += direction;
// 		if (contrast == 0xFF) { direction = -1; }
// 		if (contrast == 0x0) { direction = 1; }
// 	}
// 	vTaskDelete(NULL);
// }

// void ssd1306TaskScroll(void *ignore) {

// 	if (!ssd1306Ready){
// 		vTaskDelete(NULL);
// 		return;
// 	}


// 	esp_err_t espRc;

// 	i2c_cmd_handle_t cmd = i2c_cmd_link_create();
// 	i2c_master_start(cmd);

// 	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
// 	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

// 	i2c_master_write_byte(cmd, 0x29, true); // vertical and horizontal scroll (p29)
// 	i2c_master_write_byte(cmd, 0x00, true);
// 	i2c_master_write_byte(cmd, 0x00, true);
// 	i2c_master_write_byte(cmd, 0x07, true);
// 	i2c_master_write_byte(cmd, 0x01, true);
// 	i2c_master_write_byte(cmd, 0x3F, true);

// 	i2c_master_write_byte(cmd, 0xA3, true); // set vertical scroll area (p30)
// 	i2c_master_write_byte(cmd, 0x20, true);
// 	i2c_master_write_byte(cmd, 0x40, true);

// 	i2c_master_write_byte(cmd, 0x2F, true); // activate scroll (p29)

// 	i2c_master_stop(cmd);
// 	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
// 	if (espRc == ESP_OK) {
// 		ESP_LOGI(tag, "Scroll command succeeded");
// 	} else {
// 		ESP_LOGE(tag, "Scroll command failed. code: 0x%.2X", espRc);
// 	}

// 	i2c_cmd_link_delete(cmd);

// 	vTaskDelete(NULL);
// }

static void ssd1306SetTextLine(uint8_t cur_page) {

	if (!ssd1306Ready){
		return;
	}


	i2c_cmd_handle_t cmd;

	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd, 0x00, true); // reset column
	i2c_master_write_byte(cmd, 0x10, true);
	i2c_master_write_byte(cmd, 0xB0 | cur_page, true); // reset page

	i2c_master_stop(cmd);
	i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
	i2c_cmd_link_delete(cmd);
}

static void ssd1306PutCharacter(uint8_t character) {

	if (!ssd1306Ready){
		return;
	}


	i2c_cmd_handle_t cmd;

	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
	i2c_master_write(cmd, font[character], FONT_WIDTH, true);

	i2c_master_stop(cmd);
	i2c_master_cmd_begin(I2C_NUM_0, cmd, I2C_TIMER);
	i2c_cmd_link_delete(cmd);
}

void ssd1306SetText(char * text) {

	uint8_t i;
	uint8_t line = 0;
	uint8_t newline = 0;

	if (!ssd1306Ready) {
		return;
	}

	ssd1306SetTextLine(line);

	uint8_t text_len = strlen(text);

	for (i = 0; i < text_len; i++) {

		if (text[i] == '\r') {
			newline = 1;
			continue;
		}

		if (text[i] == '\n') {
			newline = 1;
			continue;
		}

		if (newline){
			line++;
			ssd1306SetTextLine(line);
			newline = 0;
		}

		ssd1306PutCharacter( (uint8_t) text[i]);
	}
}


void ssd1306Init(void) {

	ssd1306PinsInit();

	vTaskDelay(I2C_TIMER);

	ssd1306ModuleInit();

	vTaskDelay(I2C_TIMER);

	ssd1306CLS();

	vTaskDelay(I2C_TIMER);

}